### ISSUE TITLE
Tie submission of validator set update to submission of transaction block

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/peggy#13]
This solves a key coordination issue of how to incentivize the person submitting the validator set update and to ensure that the validator set remains updated.

The main problem here is how exactly do we want to tie these two actions? I think the easy way is to just to have batches come with a minimum required valset.

If valset x exists when a batch is created then the batch is not valid to submit until valset x or greater is on the bridge. I'm not sure if this produces any other problems we need to worry about. Also it seems kinda wasteful to do this in two calls since validating the signature costs so much.

**Comment by jkilpatr** [comment]
Action item is that @jtremback  and I should think this over. Not a target for september goal

**Comment by jtremback** [comment]
I don't think this is a good idea in its current form. It will create weird inconsistencies where tx batches that have a valset waiting on them are going to need to have higher fees in them or something, and they will probably take longer until someone submits them. This will likely be gameable by someone who can get some benefit by selectively delaying transactions by causing valset updates. If we think that the cost of valset updates is going to be a problem, we need to think of something better to fix it.

**Comment by jtremback** [comment]
Me and Justin just talked about this, and we will try making an endpoint that does both a valset and txbatch at once. Then this could be used for every single txbatch. We hadn't done this at first because we wanted to save gas on the txbatches, but since there is a lot of duplicated work, it may not make a big difference. 

There will be some additional overhead though which will result in higher average tx latency, but this may not be a big deal. I'll report back with gas test results.

**Comment by jtremback** [comment]
Here are some stats:

At 100 transactions in batch
submitBatch: 3372655 gas (~93 EUR)
updateValsetAndSubmitBatch: 3545157 gas (~98 EUR)

At 10 transactions in batch
submitBatch: 705566 gas (~17 EUR)
updateValsetAndSubmitBatch: 885463 gas (~22 EUR)

Looks like it's clearly a minor source of additional overhead.

**Comment by jkilpatr** [comment]
These are pretty good results and it seems like we clearly want to go forward with this operation from a cost perspective. 

Now it's time to consider what potential new edge cases we open up. Can we continue to consider TX batch creation and valset update creation separate operations?

The only new complexity that immediately comes to mind is what if someone tries to submit a batch with a valid valset nonce but invalid txbatch nonce or vice versa (lets say two batches where created one after another with the same valset nonce). 

Should we
1. Make it impossible to produce a new batch without updating the validator set (probably best)
2. Make the contract permit submission of mutliple batches with the same validator set

I think (1) is the clear winner. It may add slightly more latency to the creation of batches but the vast majority of latency should come from Ethereum and simply collecting enough transactions to justify the batch cost in the first place.

Perhaps the creation of the batch should replace ValSetRequest and ValSetConfirm? A txbatch is created along with a valset update when a MsgRequestBatch is sent and MsgBatchConfirm confirms both the validator set and the batch.

**Comment by jtremback** [comment]
I think 1. is likely great, but we should nail down the txbatch logic first to have a clear idea of what we're dealing with. Until then, it's acceptable to keep the split methods IMO, because there is currently money available to subisdize valset updates, so it wouldn't kill us to ship with the split methods.
