### ISSUE TITLE
"Fair" incentive for batch submission

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#15]
In the ETH [contract](https://github.com/althea-net/peggy/blob/master/solidity/contracts/Peggy.sol#L301) the (cosmos sender) fees just goes to the batch msg sender (on ETH). This may create a race condition for orchestrators that should be avoided in order to not burn ETH and be fair to all participants.

Another fairness aspect is the distribution of power on the chain. Some validators have higher stakes and take a higher risk than others on the bottom.
In the ideal case this should be considered in the fee distribution as well.

Maybe the fees could be used to compensate the senders fees (if possible) so that they not run out of ETH accidentally and the rest may go to a pool for other compensations, slashing and/or reward distribution to the group.

**Comment by jkilpatr** [comment]
@jtremback  has been working on this today. 

We have combined the validator setup update endpoint and the transaction batch submission endpoint. Such that submitting a transaction batch will also pay for a validator set update.

this as the advantage of being cheaper than doing both operations separately in exchange for the disadvantage of doing everything at once and being that much harder to reason about.

For the time being though I believe we will use the separate endpoints. Since this would be entirely an orchestrator change anyway it's not that much of a problem to switch over after we spend some time reasoning about the incentives here.

**Comment by jtremback** [comment]
@jkilpatr as far as i can tell, @alpe is referring to the tx batch submission, not the valset submission here. If that is the case, here is my take:

Relayers will compete to bring transactions over to Ethereum because they want the transaction fees. Any gas that is wasted by a relayer who loses the race to submit a batch is just a cost of doing business. The worst thing it will do is force users to include higher fees to have their tx included in a submitted batch than they would otherwise. So this is a simple matter of optimization.

IIRC most or all of the spent gas is refunded when a contract has an error and reverts. We can probably optimize the contract a bit further to make sure that it reverts as quickly as possible when someone else has already submitted the same batch.

**Comment by alpe** [comment]
> We have combined the validator setup update endpoint and the transaction batch submission endpoint

👍  That makes sense. Only the diff in the valSet needs to be attached which is probably empty most of the time.

>... @alpe is referring to the tx batch submission

Yes, that is the scenario for a race condition to get the incentive or even worse to drop non profitable messages to the ETH side.
These economics are not my domain of experience but they will have big impact on achieving the goals of the peggy bridge in practice. So I would suggest we keep this issue as a task for the future and discuss the goals and incentives/ slashing in a bigger group for a later milestone.

**Comment by jkilpatr** [comment]
> Yes, that is the scenario for a race condition to get the incentive or even worse to drop non profitable messages to the ETH side.
> These economics are not my domain of experience but they will have big impact on achieving the goals of the peggy bridge in practice. So I would suggest we keep this issue as a task for the future and discuss the goals and incentives/ slashing in a bigger group for a later milestone.

Agreed. Right now I'm still working on getting validator set updates and batch separately, we can combine them once they work individually since most of the issue at the moment is signing and orchestration. There may be some issues we need to resolve to combine these conceptually separate operations.

**Comment by jkilpatr** [comment]
I think this is resolved by #13  and can be closed as a design issue with a code solution on it's way.
